### ISSUE TITLE
feat/hero

### ISSUE THREAD

**Issue by rrand0m** [Nguyen1337/parpa#2]
https://github.com/Nguyen1337/parpa/blob/9bae0aff5d2f5962e88a0356f8812108a811a6ff/src/css/styles.css#L97

лучше не указывать нецелые числа. Если хочется указать что-то относительное лучше в процентах

**Comment by Nguyen1337** [comment]
это я использовал эту функцию 
@function vw($value, $base: 1440) {
  @return $value / $base * 100vw;
}

типо вводишь 
font-size: vw(число пикселей макета), к примеру font-size: vw(14); 
и он за базу возьмет 1440 пикселей как в макете и для него будет 14 пикселей, а дальше будет скейлиться в относительности к новой ширине экрана. по этому подбор vw идёт автоматом

**Comment by Nguyen1337** [comment]
начиная с ширины 1023 пикселя уже переход в измерения пиксельные, vw не использую. чисто потому что макет 1440 максимальный и не было пустот по бокам как до этого, 1440px и выше на вьюпортах оформлено

**Comment by rrand0m** [comment]
лучше сделать hero тогда в процентах от родителя width, без паддингов. если не выходит что процент целое число, тогда сделать просто calc(ширина блока по дизайну / 100%) Отцентровать margin: 0 auto

**Comment by Nguyen1337** [comment]
@include desktop {
      max-width: calc(1024px - 180px);
      margin: 0 auto;
    }
    
    у меня так и идёт начиная с ширины 1439 пикселей. а выше почему так не сделал, потому что там паддинги слева и справа разные. сложный макет

**Comment by rrand0m** [comment]
max-width: calc(1024px - 180px); - calc применять лучше когда у тебя есть что то относительное, типа процентов (calc(100% - 180px) 
В данном случае можно же сразу посчитать что 1024px - 180px это 844px и написать max-width: 844px

**Comment by Nguyen1337** [comment]
ага, тупанул

**Comment by Nguyen1337** [comment]
исправил
